Global Variables

In [4]:
# ANSI escape codes for colored output
GREEN = "\033[92m"
BLUE = "\033[94m"
YELLOW = "\033[93m"
RED = "\033[91m"
RESET = "\033[0m"  # White

# 1. Introduction

## Qu'est-ce que TensorFlow ?

### Présentation de TensorFlow

**TensorFlow** est une bibliothèque open-source développée par Google pour le Machine Learning et le Deep Learning. Lancée en 2015, elle est conçue pour faciliter la création, l'entraînement et le déploiement de modèles d'apprentissage automatique. TensorFlow permet de réaliser des calculs numériques complexes en utilisant des graphes de flux de données, ce qui la rend particulièrement adaptée pour le traitement de grandes quantités de données.

**Pourquoi TensorFlow est-il important ?**

- **Flexibilité** : TensorFlow supporte une variété de modèles, des réseaux de neurones simples aux architectures complexes comme les Convolutional Neural Networks (CNN) et les Recurrent Neural Networks (RNN).
- **Portabilité** : Les modèles TensorFlow peuvent être déployés sur différentes plateformes, y compris les ordinateurs personnels, les serveurs, les appareils mobiles et les navigateurs web.
- **Communauté Active** : En tant que projet open-source soutenu par Google, TensorFlow bénéficie d'une large communauté de développeurs qui contribuent à son amélioration continue.
- **Intégration avec Keras** : TensorFlow intègre Keras, une API haut niveau qui simplifie la construction et l'entraînement de modèles de Deep Learning.

### Applications courantes de TensorFlow dans l'industrie et la recherche

TensorFlow est utilisé dans de nombreux domaines pour résoudre une variété de problèmes complexes :

- **Vision par Ordinateur** : Reconnaissance d'images, détection d'objets, segmentation d'images.
- **Traitement du Langage Naturel (NLP)** : Traduction automatique, analyse de sentiments, génération de texte.
- **Reconnaissance Vocale** : Transcription de la parole en texte, assistants vocaux.
- **Systèmes de Recommandation** : Suggestions personnalisées de produits, films, musique.
- **Séries Temporelles** : Prévisions financières, analyses météorologiques.
- **Recherche Médicale** : Diagnostic assisté par IA, analyse d'images médicales, découverte de médicaments.

**Exemples concrets :**

- **Google Translate** utilise TensorFlow pour améliorer la qualité de ses traductions en utilisant des modèles de Deep Learning.
- **Airbnb** optimise ses résultats de recherche et recommandations en analysant les préférences des utilisateurs avec TensorFlow.
- **Uber** utilise TensorFlow pour prédire la demande de trajets et optimiser les itinéraires.

### Pourquoi apprendre TensorFlow ?

Apprendre TensorFlow vous permettra de :

- **Comprendre les fondements du Deep Learning** et comment construire des modèles performants.
- **Résoudre des problèmes complexes** dans divers domaines en utilisant des techniques avancées d'apprentissage automatique.
- **Améliorer votre employabilité** dans un marché du travail où les compétences en IA et en Deep Learning sont de plus en plus recherchées.

---

**Note :** Dans les sections suivantes, nous allons explorer comment installer TensorFlow, comprendre ses composants de base, et construire notre premier modèle de Deep Learning.

# 2. Installation et Configuration

## Installer TensorFlow

### Installation avec `pip`

La méthode la plus courante pour installer TensorFlow est d'utiliser `pip`, le gestionnaire de paquets pour Python.

#### Prérequis

- **Python +3.10** : Assurez-vous d'avoir une version compatible de Python installée sur votre système.
- **pip** : Généralement installé avec Python. Vous pouvez vérifier sa version avec `pip --version`.

#### Étapes d'installation

1. **Mettre à jour `pip`**

   ```bash
   pip install --upgrade pip
   ```

2. **Installer TensorFlow**

   Pour installer la dernière version stable de TensorFlow :

   ```bash
   pip install tensorflow
   ```

   Si vous disposez d'une carte graphique compatible avec CUDA et que vous souhaitez utiliser l'accélération GPU :

   ```bash
   pip install tensorflow-gpu
   ```

   **Note :** L'installation GPU nécessite des configurations supplémentaires (CUDA Toolkit et cuDNN).


### Vérification de l'installation

Après l'installation, vous pouvez vérifier que TensorFlow est correctement installé en exécutant les commandes suivantes dans un interpréteur Python :

```python
import tensorflow as tf
print(tf.__version__)
```

Si aucune erreur n'apparaît et que la version de TensorFlow s'affiche, l'installation est réussie.

## Configuration de l'environnement

### Utilisation de Google Colab

Pour éviter les problèmes d'installation et commencer rapidement, vous pouvez utiliser **Google Colab**, un service gratuit qui vous permet d'exécuter des notebooks Jupyter dans le cloud.

#### Avantages de Google Colab

- **Pas d'installation nécessaire** : Accès immédiat à un environnement Python avec TensorFlow préinstallé.
- **Accélération GPU gratuite** : Possibilité d'utiliser des GPU pour accélérer l'entraînement des modèles.
- **Partage facile** : Partagez vos notebooks avec d'autres personnes via Google Drive.

#### Comment accéder à Google Colab

1. Rendez-vous sur [Google Colab](https://colab.research.google.com/).
2. Connectez-vous avec votre compte Google.
3. Créez un nouveau notebook en cliquant sur "Nouveau Notebook".

3. **Installer TensorFlow dans l'environnement virtuel**

   ```bash
   pip install --upgrade pip
   pip install tensorflow
   ```

### Notes supplémentaires

- **Gestion des versions** : Assurez-vous que la version de TensorFlow installée est compatible avec votre version de Python.
- **Problèmes courants** : En cas de problèmes lors de l'installation, consultez la [documentation officielle de TensorFlow](https://www.tensorflow.org/install) pour des instructions détaillées.

---

**Conseil :** Si vous débutez, il est fortement recommandé d'utiliser Google Colab pour éviter les complexités liées à l'installation et pour bénéficier de l'accélération GPU sans configuration supplémentaire.

Dans les sections suivantes, nous utiliserons principalement des notebooks Jupyter, que ce soit localement ou via Google Colab, pour écrire et exécuter notre code TensorFlow.

In [ ]:
#installer tensorflow

In [1]:
#vérifier son installation

import tensorflow as tf
print(tf.__version__)

2.18.0


# 3. Premiers Pas avec TensorFlow

## Les Tenseurs

### Comprendre ce qu'est un tenseur

Un **tenseur** est la structure de données fondamentale de TensorFlow. Il s'agit d'une généralisation des vecteurs et des matrices à des dimensions potentiellement supérieures. En termes simples, un tenseur est un tableau multidimensionnel qui contient des éléments de même type.

**Dimensions des tenseurs :**

- **Scalaire (0-D tenseur)** : Un seul nombre.
- **Vecteur (1-D tenseur)** : Une liste de nombres.
- **Matrice (2-D tenseur)** : Une grille de nombres (tableau à deux dimensions).
- **Tenseur de rang N** : Un tableau N-dimensionnel.

![Scalaire_Vecteur_Matrice_Tenseur de rang N](https://miro.medium.com/v2/resize:fit:2000/1*bJfG0fYzsYPOreyztcq6NA.png)

**Pourquoi les tenseurs sont-ils importants ?**

Les tenseurs permettent de représenter des données de différentes formes et dimensions, ce qui est essentiel pour le traitement de données complexes comme les images, les textes ou les séries temporelles en Deep Learning.

### Création et manipulation de tenseurs avec TensorFlow

Commençons par importer TensorFlow :

```python
import tensorflow as tf
```

#### Création de tenseurs

1. **Tenseurs constants :**

   Utilisez `tf.constant` pour créer un tenseur immuable.

   ```python
   # Scalaire
   scalar = tf.constant(3)
   print("Scalaire :", scalar)
   ```

   ```python
   # Vecteur
   vector = tf.constant([1.0, 2.0, 3.0])
   print("Vecteur :", vector)
   ```

   ```python
   # Matrice
   matrix = tf.constant([[1, 2],
                         [3, 4]])
   print("Matrice :", matrix)
   ```

2. **Tenseurs aléatoires :**

   Utilisez `tf.random` pour créer des tenseurs avec des valeurs aléatoires.

   ```python
   random_tensor = tf.random.uniform(shape=(2, 2), minval=0, maxval=1)
   print("Tenseur aléatoire :", random_tensor)
   ```

3. **Tenseurs remplis de zéro ou de un :**

   ```python
   zeros = tf.zeros(shape=(2, 2))
   ones = tf.ones(shape=(3, 3))
   print("Zeros :", zeros)
   print("Ones :", ones)
   ```

#### Propriétés des tenseurs

- **Type de données (`dtype`)** : Type des éléments du tenseur (ex : `tf.float32`, `tf.int32`).
- **Forme (`shape`)** : Dimensions du tenseur.

```python
print("Type de données :", vector.dtype)
print("Forme du vecteur :", vector.shape)
```

#### Manipulation des tenseurs

1. **Indexation et slicing :**

   ```python
   # Accéder au premier élément du vecteur
   first_element = vector[0]
   print("Premier élément :", first_element)

   # Slicing d'une matrice
   sub_matrix = matrix[:, 0]
   print("Première colonne de la matrice :", sub_matrix)
   ```

2. **Changement de forme (reshaping) :**

   ```python
   reshaped = tf.reshape(vector, [3, 1])
   print("Vecteur reshaped :", reshaped)
   ```

3. **Conversion en tableau NumPy :**

   ```python
   numpy_array = vector.numpy()
   print("Tableau NumPy :", numpy_array)
   ```

## Opérations de Base

### Opérations mathématiques simples

TensorFlow fournit une variété d'opérations mathématiques que vous pouvez effectuer sur les tenseurs.

1. **Addition et soustraction :**

   ```python
   a = tf.constant([1, 2, 3])
   b = tf.constant([4, 5, 6])

   addition = tf.add(a, b)
   soustraction = tf.subtract(a, b)

   print("Addition :", addition)
   print("Soustraction :", soustraction)
   ```

2. **Multiplication et division :**

   ```python
   multiplication = tf.multiply(a, b)
   division = tf.divide(b, a)

   print("Multiplication :", multiplication)
   print("Division :", division)
   ```

3. **Opérations mathématiques avancées :**

   ```python
   # Exponentielle
   exp = tf.exp(a)
   print("Exponentielle :", exp)

   # Racine carrée
   sqrt = tf.sqrt(tf.cast(b, tf.float32))
   print("Racine carrée :", sqrt)
   ```

### Utilisation des variables et constantes

#### Constantes

Les constantes sont des valeurs immuables définies à l'aide de `tf.constant`.

```python
const = tf.constant(10)
print("Constante :", const)
```

#### Variables

Les variables sont des tenseurs dont les valeurs peuvent être modifiées après leur création. Elles sont créées avec `tf.Variable` et sont principalement utilisées pour stocker les poids et les biais dans les modèles d'apprentissage.

```python
var = tf.Variable(5)
print("Variable initiale :", var)

# Mise à jour de la variable
var.assign(10)
print("Variable mise à jour :", var)
```

#### Différence entre variables et constantes

- **Constantes (`tf.constant`)** : Immuables après leur création.
- **Variables (`tf.Variable`)** : Muables, leur valeur peut être modifiée.

#### Exemple d'utilisation des variables

Supposons que vous souhaitiez modéliser l'équation linéaire `y = mx + b`, où `m` et `b` sont des variables.

```python
# Initialisation des variables
m = tf.Variable(0.5)
b = tf.Variable(1.0)

# Fonction linéaire
def linear_function(x):
    return m * x + b

# Calcul pour x = 2
x = tf.constant(2.0)
y = linear_function(x)
print("Résultat de y pour x=2 :", y)
```

**Mise à jour des variables :**

Vous pouvez mettre à jour les variables en utilisant les méthodes `assign`, `assign_add`, ou `assign_sub`.

```python
# Augmenter m de 0.1
m.assign_add(0.1)
print("Nouvelle valeur de m :", m)

# Recalculer y avec le nouveau m
y_new = linear_function(x)
print("Nouveau résultat de y pour x=2 :", y_new)
```

---

**Note :** Les variables sont essentielles lors de l'entraînement des modèles, car les algorithmes d'optimisation ajustent les variables (poids) pour minimiser la fonction de perte.

In [ ]:
# A vous de jouer

### Exercice : Création et Manipulation de Tenseurs avec TensorFlow

Dans cet exercice, vous allez explorer les concepts de base des tenseurs et les manipulations fondamentales en utilisant TensorFlow. L'objectif est de vous familiariser avec la création, les propriétés, et les opérations de base sur les tenseurs.

#### Étapes :

1. **Création de tenseurs :**
   - Créez un **scalaire** de valeur 7.
   - Créez un **vecteur** avec les valeurs `[1.5, 2.5, 3.5]`.
   - Créez une **matrice** 2x2 contenant les nombres `[[1, 2], [3, 4]]`.
   - Créez un **tenseur aléatoire** de taille 3x3 avec des valeurs comprises entre 0 et 5.


In [19]:
# 1. Création de tenseurs :

print(f"{YELLOW}Création de tenseurs :{RESET}")

# Créez un scalaire de valeur 7
scalaire = tf.constant(7)
print(f"\n{GREEN}Scalaire :{RESET}\n{scalaire}")

# Créez un vecteur avec les valeurs [1.5, 2.5, 3.5]
vecteur = tf.constant([1.5, 2.5, 3.5])
print(f"\n{GREEN}Vecteur :{RESET}\n{vecteur}")

# Créez une matrice 2x2 contenant les nombres [[1, 2], [3, 4]]
matrice = tf.constant([[1, 2], [3, 4]])
print(f"\n{GREEN}Matrice :{RESET}\n{matrice}")

# Créez un tenseur aléatoire de taille 3x3 avec des valeurs comprises entre 0 et 5
tenseur_aleatoire = tf.random.uniform(shape=(3, 3), minval=0, maxval=5)
print(f"\n{GREEN}Tenseur aléatoire :{RESET}\n{tenseur_aleatoire}")

Création de tenseurs :

Scalaire :
7

Vecteur :
[1.5 2.5 3.5]

Matrice :
[[1 2]
 [3 4]]

Tenseur aléatoire :
[[1.9271749  4.4385095  1.9818717 ]
 [4.2757564  3.700236   4.4276543 ]
 [2.7749557  4.0268793  0.19180954]]


2. **Propriétés des tenseurs :**
   - Affichez le **type de données** (`dtype`) et la **forme** (`shape`) du vecteur créé à l’étape précédente.

In [20]:
# 2. Propriétés des tenseurs :

# Affichez le type de données (dtype) et la forme (shape) du vecteur
print(f"{YELLOW}Propriétés du vecteur :{RESET}\n")
print(f"{GREEN}Type de données (dtype) :{RESET}\n{vecteur.dtype}\n")
print(f"{GREEN}Forme (shape) :{RESET}\n{vecteur.shape}")


Propriétés du vecteur :

Type de données (dtype) :
<dtype: 'float32'>

Forme (shape) :
(3,)


3. **Manipulation de tenseurs :**
   - Utilisez l'**indexation** pour accéder au premier élément du vecteur.
   - Utilisez le **slicing** pour obtenir la première colonne de la matrice.
   - **Reshapez** le vecteur pour obtenir une forme de `(3, 1)`.
   - **Convertissez** le vecteur en tableau NumPy et affichez le résultat.

In [22]:
# 3. Manipulation de tenseurs :

print(f"{YELLOW}Manipulation de tenseurs :{RESET}\n")

# Utilisez l'indexation pour accéder au premier élément du vecteur
premier_element = vecteur[0]
print(f"{GREEN}Premier élément du vecteur (indexation) :\n{RESET} {premier_element}")

# Utilisez le slicing pour obtenir la première colonne de la matrice
premiere_colonne = matrice[:, 0]
print(f"\n{GREEN}Première colonne de la matrice (slicing) :{RESET}\n{premiere_colonne}")

# Reshapez le vecteur pour obtenir une forme de (3, 1)
vecteur_reshape = tf.reshape(vecteur, (3, 1))
print(f"\n{GREEN}Vecteur reshape en (3, 1) :{RESET}\n{vecteur_reshape}")

# Convertissez le vecteur en tableau NumPy et affichez le résultat
vecteur_numpy = vecteur.numpy()
print(f"\n{GREEN}Vecteur converti en tableau NumPy :\n{RESET} {vecteur_numpy}")

Manipulation de tenseurs :

Premier élément du vecteur (indexation) :
 1.5

Première colonne de la matrice (slicing) :
[1 3]

Vecteur reshape en (3, 1) :
[[1.5]
 [2.5]
 [3.5]]

Vecteur converti en tableau NumPy :
 [1.5 2.5 3.5]


4. **Opérations mathématiques sur les tenseurs :**
   - Créez deux vecteurs `a` et `b` de tailles égales.
   - Effectuez une **addition**, une **soustraction**, une **multiplication**, et une **division** entre les deux vecteurs.
   - Calculez l'**exponentielle** des éléments du vecteur `a` et la **racine carrée** des éléments de `b`.

In [23]:
# 4. Opérations mathématiques sur les tenseurs :

print(f"\n{YELLOW}Opérations mathématiques sur les tenseurs :{RESET}\n")

# Créez deux vecteurs `a` et `b` de tailles égales
a = tf.constant([2.0, 4.0, 6.0])
b = tf.constant([1.0, 2.0, 3.0])

print(f"{GREEN}Vecteur a :{RESET} {a}")
print(f"{GREEN}Vecteur b :{RESET} {b}\n")

# Addition
addition = tf.add(a, b)
print(f"{GREEN}Addition :{RESET} {addition}")

# Soustraction
soustraction = tf.subtract(a, b)
print(f"{GREEN}Soustraction :{RESET} {soustraction}")

# Multiplication
multiplication = tf.multiply(a, b)
print(f"{GREEN}Multiplication :{RESET} {multiplication}")

# Division
division = tf.divide(a, b)
print(f"{GREEN}Division :{RESET} {division}\n")

# Calculez l'exponentielle des éléments du vecteur `a`
exponentielle = tf.exp(a)
print(f"{GREEN}Exponentielle des éléments de a :{RESET} {exponentielle}")

# Calculez la racine carrée des éléments du vecteur `b`
racine_carre = tf.sqrt(b)
print(f"{GREEN}Racine carrée des éléments de b :{RESET} {racine_carre}")


Opérations mathématiques sur les tenseurs :

Vecteur a : [2. 4. 6.]
Vecteur b : [1. 2. 3.]

Addition : [3. 6. 9.]
Soustraction : [1. 2. 3.]
Multiplication : [ 2.  8. 18.]
Division : [2. 2. 2.]

Exponentielle des éléments de a : [  7.389056  54.59815  403.4288  ]
Racine carrée des éléments de b : [1.        1.4142135 1.7320508]


5. **Utilisation des constantes et des variables :**
   - Créez une **constante** avec la valeur `5`.
   - Créez une **variable** initialisée à `2`.
   - Modifiez la valeur de la variable pour `10` en utilisant `assign`.
   - Créez une fonction linéaire `y = mx + b`, où `m` et `b` sont des variables.
   - Calculez la valeur de `y` pour `x = 3`.

In [25]:
# 5. Utilisation des constantes et des variables :

print(f"\n{YELLOW}Utilisation des constantes et des variables :{RESET}\n")

# Créez une constante avec la valeur `5`
constante = tf.constant(5)
print(f"{GREEN}Constante :{RESET} {constante}")

# Créez une variable initialisée à `2`
variable = tf.Variable(2)
print(f"{GREEN}Variable initialisée :{RESET} {variable.numpy()}")

# Modifiez la valeur de la variable pour `10` en utilisant `assign`
variable.assign(10)
print(f"{GREEN}Variable après modification avec assign :{RESET} {variable.numpy()}\n")

# Créez une fonction linéaire `y = mx + b`, où `m` et `b` sont des variables
m = tf.Variable(2.0)  # Slope
b = tf.Variable(1.0)  # Intercept

# Calculez la valeur de `y` pour `x = 3`
x = tf.constant(3.0)
y = m * x + b
print(f"{GREEN}Valeur de y (pour x = 3) dans la fonction linéaire y = mx + b :{RESET} {y}")


Utilisation des constantes et des variables :

Constante : 5
Variable initialisée : 2
Variable après modification avec assign : 10

Valeur de y (pour x = 3) dans la fonction linéaire y = mx + b : 7.0
